export default {
  ServerUrl: '127.0.0.1:3000',
  // baseUrl: "http://coastalmedbackend.dignitech.com/",
  // baseUrl: "http://coastalcarefl.com",
  baseUrl: 'http://52.87.3.228:5500',

  login: '/api/v1/Appregister/loginUser',
  register: '/api/v1/account/register/',
  otp: '/api/v1/Appregister/verifyOTP',
  resendotp: '/api/v1/Appregister/resendOTP',
  getParentCatogary: '/api/v1/ParentCategory/Parentcategory',
  getoffers4u: '/api/v1/OffersForYou/offersForYou',
  getHeroSlider: '/api/v1/HeroSlider/GetHeroSlider',
  getBrandweuse: '/api/v1/BrandWeUse/GetBrandWeUse?parentId=',
  getFaqs: '/api/v1/Faqs/GetFaqs?parentId=',
  getVideoShortcut: '/api/v1/VideoShortcut/VGetShortcute',
  getChildCategoryNames: '/api/v1/ChildCategory/NameChildcategory',
  getTestinomial: '/api/v1/Testimonials/GetTestimonials?parentId=',
  getChildCategory: '/api/v1/ChildCategory/GetChildcategory?parentId=',
  getServiceGroup: '/api/v1/ServiceGroup/geterviceGroup',
  getHomeBottom: '/api/v1/HomeBottomBanners/GetHomeBanner',
  getChildCTopBanner: '/api/v1/parentSlider/GetSlider?parentId=',
  getDatabyHeading: '/api/v1/VideoShortcut/GetDataByHeading/',
  getHeadings: '/api/v1/VideoShortcut/GetHeading',
  OtherCharges: '/api/v1/OtherCharges/OtherChargeByPId',
  GetAppointments: '/api/v1/AppoinmentSlot/GetStatusButton',
  getPackagesOrServices: '/api/v1/Service/servicepackagebychild?childId=',
  EditProfile: '/api/v1/Appregister/updateUser/',
  CreateProfile: '/api/v1/Appregister/addData',
  getUserDetails: '/api/v1/Appregister/getUser/',
  AddAddress: '/api/v1/Address/CreateAddress',
  getSavedAddress: '/api/v1/Address/GetAddress?CreatedBy=',
  deleteAddress: '/api/v1/Address/DeleteAddress/',
  SearchServices: '/api/v1/Service/servicepackagebyKeywords?keyword=',
  getTrendingServices: '/api/v1/Tranding/GetTranding',
  getCoverImage: '/api/v1/CoverImage/GetCoverImage',
  serviceShortcut: '/api/v1/ServiceShortcut/GetShortcute',
  AddJobs: '/api/v1/jobs/AddjobsApp',
  MyBokings: '/api/v1/jobs/getjobs',
  verifyOrder: '/api/v1/jobs/orderVerfy',
  getCoupen: '/api/v1/coupons/getCoupon',
  reshedule: '/api/v1/jobs/update-appointment/',
  cancelBooking: '/api/v1/jobs/cancel-job/',
  editAddressEndpoint: '/api/v1/Address/UpdateAddress/',
};
